name: vulcanizing_app_ignite_creative
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  firebase_dynamic_links: ^5.5.0
  firebase_ui_auth: ^1.13.1
  cloud_firestore: ^4.16.0
  firebase_database: ^10.5.0
  geolocator: ^7.0.3
  flutter_rating_bar: ^4.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
